### PR TITLE
add -b to launch bash shell in docker container

### PR DESCRIPTION
**Pull request by nam20485**
* **Please check if the PR fulfills these requirements**

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Included your name and github handle in the contributors.md - Contributors section
- [ ] Major/Breaking Changes are listed in Changelog

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Feature/Enhancement

* **What is the current behavior?** (You can also link to an open issue here)

No way to run bash shell inside running Docker image

* **What is the new behavior (if this is a feature change)?**

`bin/start.sh -b` now launches bash shell running inside of Docker container

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

* **Other information**:

### CODE REVIEW

**Review by znmeb — COMMENTED** [review]
I'm not sure why one would do this instead of starting the container normally and doing `docker exec -it <container-name> /bin/bash`.

**Comment by nam20485** [comment]
@znmeb I think it does the same thing. Is `docker exec` the preferred way?

**Comment by znmeb** [comment]
@nam20485 I don't think there's a preference. If you do `start.sh -b` it won't execute the Django startup, so you'd see the state of the container before it started. If you wanted to edit something before starting it, you'd need the `-b` option. But we'd have to install editors with `apt install` - I don't think they're on the image.

I think this may be a "You'll need it when ..." - something that's easy to add if we actually need it/

**Comment by nam20485** [comment]
OK that makes sense. The only reason I use it is to open a shell to the container and run `python manage.py makemigrations` and then grab a copy of the migrations. So in that case I don't need the Django startup to happen.

Does the `docker exec` method perform the Django startup?

**Comment by znmeb** [comment]
@nam20485 No, `docker exec -it <container-name> /bin/bash` would give you a shell. Then you would `cd` to the correct place if it's not the default and do `python manage.py makemigrations`. Then you'd exit the shell and do `docker cp <migrations-file> .` and move the file where you want it.

But why are we doing all this troubleshooting? Doesn't the default entry point make the migrations already?

**Comment by nam20485** [comment]
No, the default entry point was not making the migrations. Or at least it wasn't until yesterday. I spent the last few days fighting #26, which I fixed last night by #27. 

During that time period I had to make my own migrations using a workaround. I used the [`docker-compose run --entrypoint bash -p 8000:8000 api`](https://github.com/hackoregon/2019-sandbox-backend/blob/da1c49e4d87e6330c27fae8f90cf8b245dfb4bac/bin/start.sh#L17) to gain a shell in to my container, then ran `python manage.py makemigrations` to create the migrations manually **inside the container**. I then took advantage of the fact that the `/code/src_files/` directory inside the container happened to be a docker shared volume, which allowed me to pop the migration files to **outside of the container** by doing a `cp <migrations> /code/src_files/ && exit`.
```
volumes:
   - .:/code/src_files/
```
Make sense? :)

**Review by bhgrant8 — CHANGES_REQUESTED** [review]
As the bin shell scripts are provided as workflow/development usage, I think adding the extra flag is fine, a few lest things to type/remember.

One change though would be to add the linux system check on rather to run with sudo:
https://github.com/hackoregon/2019-backend-cookiecutter-django/blob/db6dd2d3f84d085d0bc7b50662e602ebc7d6944b/%7B%7Bcookiecutter.github_repo%7D%7D/bin/start.sh#L10

which is in relation to this issue:

https://github.com/hackoregon/2019-backend-cookiecutter-django/issues/10

**Comment by nam20485** [comment]
> One change though would be to add the linux system check on rather to run with sudo:
2019-backend-cookiecutter-django/{{cookiecutter.github_repo}}/bin/start.sh

> Line 10 in db6dd2d

>  if [ `uname -s` = "Linux" ] 
> which is in relation to this issue:

> #10

Done

**Comment by znmeb** [comment]
@nam20485 @bhgrant8 You're testing for Linux on all the scripts, right?

**Comment by nam20485** [comment]
Yes I tested my change on Linux.

**Pull request merged**
