### PR TITLE
Development

### PR DESCRIPTION
**Pull request by bhgrant8**
* **Please check if the PR fulfills these requirements**

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] Included your name and github handle in the contributors.md - Contributors section
- [x] Major/Breaking Changes are listed in Changelog

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

This PR provides a bug fix as well as adds bug report and feature request templates

* **What is the current behavior?** (You can also link to an open issue here)

See #12 and #9 

* **What is the new behavior (if this is a feature change)?**

Installed app properly calls the app name from the apps.py file:
https://github.com/hackoregon/2019-backend-cookiecutter-django/blob/master/%7B%7Bcookiecutter.github_repo%7D%7D/%7B%7Bcookiecutter.python_package_namespace%7D%7D/%7B%7Bcookiecutter.python_subpackage%7D%7D/apps.py#L5

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

Non breaking change

* **Other information**:

### CODE REVIEW

**Review by znmeb — COMMENTED** [review]
I think we need both `django.contrib.gis` and `rest_framework_gis` in `INSTALLED_APPS` - I think they're imported at two different times.

**Comment by jbeyer16** [comment]
Looks good to me. That fix for #12 worked for me. Thanks for collecting it into an issue.

**Review by geophpherie — COMMENTED** [review]
Looks good to me. That fix for #12 worked for me. Thanks for collecting it into an issue.

**Comment by bhgrant8** [comment]
going to merge, will address question of gis app in another issue

**Pull request merged**
