### PR TITLE
Development

### PR DESCRIPTION
**Pull request by bhgrant8**
* **Please check if the PR fulfills these requirements**

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] Included your name and github handle in the contributors.md - Contributors section
- [x] Major/Breaking Changes are listed in Changelog

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
https://github.com/hackoregon/2019-backend-cookiecutter-django/issues/10

* **What is the new behavior (if this is a feature change)?**

sudo is now used to run docker and docker-compose commands

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

should not be breaking change

* **Other information**:

### CODE REVIEW

**Review by znmeb — COMMENTED** [review]
We should probably check this on a Mac before we commit it. I think Jeff was surprised when it asked for his password, since `sudo` isn't necessary on Macs.

**Comment by bhgrant8** [comment]
> We should probably check this on a Mac before we commit it. I think Jeff was surprised when it asked for his password, since `sudo` isn't necessary on Macs.

I am also asked for password on Mac because of the sudo, but if it was blocking folks, was willing to add.

Also added fix for #8, issue was bash not recognizing `True` vs `true`. Added lowercasing to variable in if statement

**Comment by znmeb** [comment]
It's pretty easy to only do the `sudo` on Linux - we're already testing for Linux at the bottom of `start.sh` when we re-own the files that came down from the container.

**Comment by bhgrant8** [comment]
@znmeb, i added the linux check logic around the sudo-ed commands. They are running on my mac w/o password, could you check on your system?

**Pull request merged**
